### ISSUE TITLE
Could you please release the pipeline for training pre-training model.

### ISSUE THREAD

**Issue by zouying-sjtu** [frotms/image_classification_pytorch#3]
Are you planed to release a pipeline for training pre-training model. If planed ,when? Thanks for your help.

**Comment by frotms** [comment]
> Are you planed to release a pipeline for training pre-training model. If planed ,when? Thanks for your help.

Actually, the url of pretrained models are in the script of each net_module.py. You could download them by yourself, and configure with your config.json. I will make a list in readme.md.
